name: Check Docker build
on: [pull_request]
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379:6379

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: create secrets
      run: |
        mkdir secrets
        printf "password" > secrets/postgres_password
        printf "my_token_key" > secrets/auth_token_key 
        printf "my_cookie_key" > secrets/auth_cookie_key

    - name: Start With Docker
      run: |
        docker build . --tag openslides-vote
        timeout --preserve-status --signal=SIGINT 5s docker run --network host -v $PWD/secrets:/run/secrets openslides-vote
      env:
        DOCKER_BUILDKIT: 1
